name: Test and Deploy to EC2

on:
  push:
    branches:
      - mainline

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
        # or `npm run test` if your package.json script is called 'test'

      - name: Set up SSH
        run: |
          sudo mkdir -p ~/.ssh
          sudo echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          sudo ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and restart PM2
        if: success()  # only run if tests pass
        run: |
          sudo ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/your-repo
            sudo git pull origin mainline
            sudo npm install
            sudo pm2 restart backend || pm2 start bin/www --name backend
          EOF
